version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    command: ["Run", "migrate", "--yes"]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
